version: "3"
services:
  app:
    image: amara-app
    command: app
    environment:
      DJANGO_SETTINGS_MODULE: dev_settings
      DJANGO_LIVE_TEST_SERVER_ADDRESS: 'localhost:8081,8090-8100,9000-9200'
      LANG: en_US.UTF-8
      WORKERS: 2
      JSON_LOGGING:
      DB_LOGGING:
    volumes:
      - .:/opt/apps/amara:z
    hostname: unisubs.example.com
    ports:
      - "8000:8000"
    depends_on:
      - db
      - queue
      - cache
      - asset-builder

  worker:
    image: amara-app
    command: worker
    environment:
      CELERY_OPTS: -B
      CELERY_QUEUES: default,priority
      DJANGO_SETTINGS_MODULE: dev_settings
      LANG: en_US.UTF-8
      JSON_LOGGING:
    volumes:
      - .:/opt/apps/amara:z
    links:
      - db
      - queue
      - cache

  feed-worker:
    image: amara-app
    command: feed_worker
    environment:
      DJANGO_SETTINGS_MODULE: dev_settings
      LANG: en_US.UTF-8
      JSON_LOGGING:
    volumes:
      - .:/opt/apps/amara:z
    depends_on:
      - db
      - queue
      - cache

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: amara
      MYSQL_USER: amara
      MYSQL_PASSWORD: amara
      MYSQL_DATABASE: amara
    volumes:
      - ./docker-dev/mysql/conf.d/:/etc/mysql/conf.d:z
    ports:
      - "3306"

  asset-builder:
    image: node:9.0.0
    volumes:
      - .:/mnt
    working_dir: /mnt/amara-assets
    command: ['node', 'node_modules/gulp/bin/gulp.js']

  queue:
    image: rabbitmq
    ports:
      - "5672"
      - "15672"

  cache:
    image: memcached
    ports:
      - "11211"

  varnish:
    image: amara/amara-cache
    ports:
      - "9000:80"
